### ISSUE TITLE
Issues with note threads

### ISSUE THREAD

**Issue by BrightonBTC** [BrightonBTC/bija#14]
Replies are not always in the correct order. Possibly an issue with positional e tags.

**Comment by ok300** [comment]
Or with the note timestamps. Local client time can be out of sync, so a Bob's reply to Alice could appear as "before" Alice's, if they're sorted by `created_at`.

Posiitional e-tags are [deprecated](https://github.com/nostr-protocol/nips/blob/master/10.md) FYI.

**Comment by BrightonBTC** [comment]
Yeah, you're right, created _at can't be completely trusted. 

Bija does use the newer 'marked' e tags - any events created on bija are marked - but also allows incoming positional ones too. Even though they're deprecated so many people are using them that I'm still supporting them for now ( it's a pain though tbh)
