### ISSUE TITLE
ModuleNotFoundError: No module named 'python_nostr.nostr.pow'

### ISSUE THREAD

**Issue by NaushBushi** [BrightonBTC/bija#19]
git clone --recurse-submodules https://github.com/BrightonBTC/bija
cd bija
docker-compose up

Result:

Creating bija_web_1 ... done
Attaching to bija_web_1
web_1  | Traceback (most recent call last):
web_1  |   File "/app/cli.py", line 1, in <module>
web_1  |     from bija.app import main
web_1  |   File "/app/bija/app.py", line 15, in <module>
web_1  |     from bija.routes import *
web_1  |   File "/app/bija/routes.py", line 15, in <module>
web_1  |     from bija.events import BijaEvents, MetadataEvent
web_1  |   File "/app/bija/events.py", line 17, in <module>
web_1  |     from bija.submissions import *
web_1  |   File "/app/bija/submissions.py", line 12, in <module>
web_1  |     from python_nostr.nostr.pow import mine_event
web_1  | ModuleNotFoundError: No module named 'python_nostr.nostr.pow'
bija_web_1 exited with code 1

**Comment by BrightonBTC** [comment]
Should work now, I just had to update the reference to the submodule _python_nostr,_ it was pointing to an older version that's missing some requirements.
