### ISSUE TITLE
lazy load user images

### ISSUE THREAD

**Issue by BrightonBTC** [BrightonBTC/bija#22]
As we're loading so many external resources it makes sense to lazy load any user images, both pfp and those embedded in posts. Slow loading images are frequently slowing down page load time, especially on main feed.

**Comment by makinTheStuff** [comment]
@BrightonBTC I would love to hop in and help if you can use an extra pair of hands. Would this be a good issue to hop into? I am new here so if you have any suggestions I'm happy to pick up a new feature, a glaring bug, testing, performance optimization, ui/ux/mobile (this is admittedly not my area of expertise but I can learn), refactoring or whatever you wish you had time to get to but cant find the time to get to. Thank you for this awesome lib!

**Comment by BrightonBTC** [comment]
This would be a great issue to work on! As I just said in my comment on your pull request, I'm undergoing a major refactor. Dealing with lazy loading images will be mostly isolated to js and template files though, and that's unlikely to conflict with anything I'm working on.

Hopefully I'll have both the code and the github a bit more organised soon so that it's easier for people to come and contribute and find issues to work on.

**Comment by makinTheStuff** [comment]
Sorry about the delay. It was a busy few days but I think I got lazy loading working. It was giving me a bit of trouble but please give it a review when you have some time 

https://github.com/BrightonBTC/bija/pull/45

**Comment by BrightonBTC** [comment]
All looks good to me! Thanks.

**Comment by makinTheStuff** [comment]
Thanks mate! I'll get going another issue tonight; any suggestions are always welcome

**Comment by BrightonBTC** [comment]
I've been adding a few needed features as issues, feel free to pick up anything on there, just drop a message on the issue so we don't work on the same thing at the same time ;)

I'm also open to suggestions and ideas if there's something else you'd like to work on.
