### ISSUE TITLE
Generates wrong mnemonic if user imports the privkey

### ISSUE THREAD

**Issue by kaichengmung** [BrightonBTC/bija#27]
If a user imports a private key to bija, and the goes to settings page to see it, the generated mnemonic phrase is invalid.
If they import that seed phrase in some other client that supports importing mnemonic phrases, they will get a different private key based on [NIP06](https://github.com/nostr-protocol/nips/blob/master/06.md)

**Comment by BrightonBTC** [comment]
Hi there, I'm unable to reproduce this issue. I've tried various different ways of producing keys, adding keys, etc. but the mnemonic I get is always consistent with what's expected.

Please note that Bija creates a 24 word mnemonic. This won't be valid in a client that is expecting a 12 word, or other length, one for example. It also won't accept different length mnemonics created elsewhere.

If this doesn't answer your issue can you supply me with some more details of which other client you're generating the mnemonic in, or trying to copy the bija mnemonic to. Thanks

**Comment by kaichengmung** [comment]
It almost answers my question, but I don't understand if the 24 words mnemonic is generated according to [NIP06](https://github.com/nostr-protocol/nips/blob/master/06.md)? Also as I understand it is not really possible to get a mnemonic phrase from a private key? 

Anyway, here is the JS script that I used to generate the seed and private key
```
const nostr = require("nostr-tools");

const seed = nostr.nip06.generateSeedWords();
const privKey = nostr.nip06.privateKeyFromSeedWords(seed)

console.log({ seed, privKey })
```
It gives the following output for example:

```
{
  seed: 'fun siege wild few drift owner gadget person own scan moon expose',
  privKey: '1bed579272ee7a2f216f078f60b42a8b8abdf0a12cc8c368ef2e0a0c508581fb'
}
```
If I am developing a client, I will show this mnemonic to my users. But if they go on and enter their private key (1bed...581fb) to bija, they will get this as this as their mnemonic:

```
Mnemonic phrase (preferred)
brief height tonight total tray bleak mad thought month aisle apple blade profit weapon lucky october sell electric slide beef shallow drift among hire
nsec
nsec1r0k40ynjaeaz7gt0q78kpdp23w9tmu9p9nyvx6809c9qc5y9s8as80sh09
HEX
1bed579272ee7a2f216f078f60b42a8b8abdf0a12cc8c368ef2e0a0c50858
```
I think it is because it is not following NIP06? Also they won't be able to use the mnemonic my client generated in bija. So that is a issue with interoperability as well

**Comment by BrightonBTC** [comment]
It is still in accordance with NIP06. 

NIP06 requires you to create the mnemonic in accordance with BIP39 and if you refer to the 'Generating the mnemonic' section of that BIP you'll see how and why there's a few different word lengths that are possible - it just depends on the entropy used.

I do intend to add support for 12 words at some point though, especially as nostr-tools js uses them, and will add it is a feature request here on github. It's likely to be a while until it's done though as there's quite a few other features higher up my priorty list ATM.

**Comment by BrightonBTC** [comment]
https://github.com/BrightonBTC/bija/issues/33
