### ISSUE TITLE
Posting from profile page yields a “400 Bad Request”

### ISSUE THREAD

**Issue by kseistrup** [BrightonBTC/bija#54]
Posting from the “Say something” box on my profile in bija yields a `400 Bad Request`:

```
Bad Request

The browser (or proxy) sent a request that this server could not understand.
```

The URL at that point is: http://localhost:5000/submit_note

* Commit: 4e81b988e4bd5abf8a3ef5214cb522a2cffe7d31
* Python: 3.10.9
* Firefox: 108.0.2

**Comment by BrightonBTC** [comment]
Thanks, yes that does seem to broken. I'm on it.

**Comment by kseistrup** [comment]
Whauw, that was fast! :smile_cat:
