### ISSUE TITLE
issues installing via pip using 3.11

### ISSUE THREAD

**Issue by ngmisl** [BrightonBTC/bija#7]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      0.29.2

**Comment by BrightonBTC** [comment]
Hi, this project is in early development and hasn't been packaged so there's no setup.py or option to install with pip. You can either run one of the binaries on the releases page, or clone the repo and follow the instructions on the readme.
